### ISSUE TITLE
fail to run the fundamental_default example 

### ISSUE THREAD

**Issue by SenHuang19** [GMLC-TDC/HELICS-Examples#69]
When running [default example ](https://github.com/GMLC-TDC/HELICS-Examples/tree/main/user_guide_examples/fundamental/fundamental_default) with the [instruction](https://docs.helics.org/en/latest/user-guide/examples/fundamental_examples/fundamental_default.html), I got the following error from the log of the <code>Charger</code>:

> Requesting time 6480.0
Granted time 9223372036.854774
EV 1 time 9223372036.854774
        Charging current: 3.87 from input Battery/EV1_current
Traceback (most recent call last):
  File "/home/developer/HELICS-Examples/user_guide_examples/fundamental/fundamental_default/Charger.py", line 184, in <module>
    h.helicsPublicationPublishDouble(pubid[j], charging_voltage[j])
  File "/usr/local/lib/python3.10/site-packages/helics/capi.py", line 7750, in helicsPublicationPublishDouble
    raise HelicsException("[" + str(err.error_code) + "] " + ffi.string(err.message).decode())
helics.capi.HelicsException: [-10] publications not allowed outside of execution and initialization state

The log of <code>helic_cli</code> is:

> helics-cli [info]: Running federation: fundamental_default
helics-cli [info]: Running federate Charger as a background process
helics-cli [info]: Running federate Battery as a background process
helics-cli [info]: Waiting for 3 processes to finish ...
Error: Process Charger has failed, killing other processes
helics-cli [error]: Process broker exited with return code -9
helics-cli [error]: Process Charger exited with return code 1
helics-cli [error]: Process Battery exited with return code 1
helics-cli [info]: Done.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/site-packages/helics_cli/status_checker.py", line 40, in run
    raise HELICSRuntimeError("Error has occurred")
helics_cli.exceptions.HELICSRuntimeError: Error has occurred

Environment: a Docker container based on [python:3-slim](https://github.com/docker-library/python/blob/5928f8feb837652b4255a8ff51fb2a467ce2e93f/3.10/slim-bullseye/Dockerfile)

**Comment by trevorhardy** [comment]
Sorry for not catching this sooner; I wasn't paying as close attention to this repo as I should have. Is this still a pending problem?

**Comment by trevorhardy** [comment]
Last chance, @SenHuang19; should I keep this open or close it out?

**Comment by SenHuang19** [comment]
Yes, it is still a problem on my end. Could you please take a look at it? Thank you so much!

**Comment by trevorhardy** [comment]
I just ran this example and it was working fine for me. Can you run  `helics --version` and post the results here? Also, can you post the contents of `broker.log` here?

**Comment by trevorhardy** [comment]
@SenHuang19, do you still need help with this?
